name: cancha_mobile
description: "Flutter application for discovering sports venues, exploring courts, and managing bookings with Cancha."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  shared_preferences: ^2.5.5
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.3.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/cancha_apk.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/cancha_apk.png"
  web:
    generate: true
    image_path: "assets/images/cancha_apk.png"
    background_color: "#FFFFFF"
    theme_color: "#2E7D32"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/cancha_logo.png
  color_dark: "#16213E"
  image_dark: assets/images/cancha_dark_logo.png
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  fullscreen: true
  android_12:
    color: "#FFFFFF"
    image: assets/images/cancha_apk.png
    color_dark: "#16213E"
    image_dark: assets/images/cancha_apk.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/cancha_logo.png
    - assets/images/cancha_dark_logo.png
    - assets/images/cancha_apk.png
    - assets/images/default_futsal.jpg
    - assets/images/default_padel.jpg
    - assets/images/default_soccer.jpg
    - assets/images/default_tennis.jpg
    - assets/images/default_perfil.jpg
